### ISSUE TITLE
Cant adjust image 

### ISSUE THREAD

**Issue by xperiafan13-rom** [firdausmaulan/GlideSlider#1]
I cant fit image to view, any solution?
I already try setCenterCrop

**Comment by firdausmaulan** [comment]
Thanks for the feedback..
Could you send the screenshot..

**Comment by kr4k3rz** [comment]
sliderView
	.image(listUrl.get(i))
	.setBitmapTransformation(new CenterCrop());
mSlide.addSlider(sliderView);`
