### ISSUE TITLE
ScaleType is missing 

### ISSUE THREAD

**Issue by prokash-sarkar** [firdausmaulan/GlideSlider#11]
Currently, there's no way to apply ScaleType on TextSliderView. The original library has the ability to apply ScaleType e.g. **.setScaleType(BaseSliderView.ScaleType.Fit)**

**Comment by firdausmaulan** [comment]
In every demo app, I'm using .centerCrop() as an example of scaling image.
You can change it to .fitCenter(), .centerInside(), .circleCrop(), or other scaling method which supported by Glide Library.

**Comment by marconealberto** [comment]
you should update the documentation then, I landed here for the same reason. Thank you anyways.
