### ISSUE TITLE
How to change default diskCacheStrategy?

### ISSUE THREAD

**Issue by takajimar** [firdausmaulan/GlideSlider#12]
I want to change the default diskCacheStrategy to show animated GIFs. Is there any way to do it?

**Comment by firdausmaulan** [comment]
try to use latest version
implementation 'com.github.firdausmaulan:GlideSlider:1.1.1'

So you can change diskCacheStrategy on Glide RequestOptions, like this : 
`RequestOptions requestOptions = new RequestOptions();
        requestOptions
                .centerCrop()
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .placeholder(R.drawable.placeholder)
                .error(R.drawable.placeholder);`

**Comment by takajimar** [comment]
It works, thank you!
This is my code:
```
RequestOptions requestOptions = new RequestOptions();
requestOptions.centerCrop().diskCacheStrategy(DiskCacheStrategy.RESOURCE);

DefaultSliderView defaultSliderView = new DefaultSliderView(this);
defaultSliderView.image(account.getMainImage())
        .empty(R.mipmap.empty)
        .error(R.mipmap.error)
        .description(account.getShopName())
        .setRequestOption(requestOptions)
        .setOnSliderClickListener(this);
demoSlider.addSlider(defaultSliderView);
```
