### ISSUE TITLE
Can't extend the BaseSliderView

### ISSUE THREAD

**Issue by bmilovanovic** [firdausmaulan/GlideSlider#13]
In the a066e8be29b82ebca839ad6d81782c3337f2429b, you changed the BaseSliderView constructor access to a package which made it impossible to extend from it (Urgent?).
It works for DefaultSliderView and TextSliderView because they're in the same package.
Am I missing something here?

EDIT: It's also an issue with the mOnSliderClickListener. At least you can make a getter for it.

**Comment by firdausmaulan** [comment]
Okay thanks for the feedback.. I already revert it to public in version 1.2.0
