### ISSUE TITLE
out of memory 

### ISSUE THREAD

**Issue by hksfho** [firdausmaulan/GlideSlider#16]
I have a tabview (3tabs)
each tab have a listview
each listview have ten items
each item have a GlideSlider
each glideslider have 5 images
each image 100kb(assets folder)

How to increase glideslider performance?

The app wil crash if I switch to the second tab and scroll down.

```


public View getView(int position, View convertView, ViewGroup parent) {
        TextView tv_title;
        SliderLayout sl_slider;
        if (convertView != null) {
            tv_title = (TextView) convertView.findViewById(R.id.tv_title);
            sl_slider = (SliderLayout) convertView.findViewById(R.id.sl_slider);
            tv_title.setText(null);
            sl_slider.stopAutoCycle();
            sl_slider.removeAllSliders();
        }
        convertView = LayoutInflater.from(context).inflate(R.layout.lv_item, null);
        tv_title = (TextView) convertView.findViewById(R.id.tv_title);
        sl_slider = (SliderLayout) convertView.findViewById(R.id.sl_slider);

        Slider slider = getItem(position);
        String title = slider.getTitle();
        ArrayList<String> imageArrayList = slider.getSlideArrayList();

        tv_title.setText(title);

        for (int i = 0; i < imageArrayList.size(); i++) {
            sl_slider.addSlider(new DefaultSliderView(context)
                    .image("file:///android_asset/" + imageArrayList.get(i) + ".png")
                    .setRequestOption(requestOptions)
                    .setBackgroundColor(Color.TRANSPARENT));
        }
        sl_slider.startAutoCycle(5000, 12000, true);

        return convertView;
    }
```

**Comment by hksfho** [comment]
`public View getView(int position, View convertView, ViewGroup parent) {
        TextView tv_title;
        SliderLayout sl_slider;
        if (convertView != null) {
            tv_title = (TextView) convertView.findViewById(R.id.tv_title);
            sl_slider = (SliderLayout) convertView.findViewById(R.id.sl_slider);
            tv_title.setText(null);
            sl_slider.stopAutoCycle();
            sl_slider.removeAllSliders();
        }
        convertView = LayoutInflater.from(context).inflate(R.layout.lv_item, null);
        tv_title = (TextView) convertView.findViewById(R.id.tv_title);
        sl_slider = (SliderLayout) convertView.findViewById(R.id.sl_slider);

        Slider slider = getItem(position);
        String title = slider.getTitle();
        ArrayList<String> imageArrayList = slider.getSlideArrayList();

        tv_title.setText(title);

        for (int i = 0; i < imageArrayList.size(); i++) {
            sl_slider.addSlider(new DefaultSliderView(context)
                    .image("file:///android_asset/" + imageArrayList.get(i) + ".png")
                    .setRequestOption(requestOptions)
                    .setBackgroundColor(Color.TRANSPARENT));
        }
        sl_slider.startAutoCycle(5000, 12000, true);

        return convertView;
    }`

**Comment by firdausmaulan** [comment]
I think you have to use viewholder pattern
[https://dzone.com/articles/optimizing-your-listview](https://dzone.com/articles/optimizing-your-listview)

and you can optimize it by resizing or scaling the image using glide override method
[https://futurestud.io/tutorials/glide-image-resizing-scaling](https://futurestud.io/tutorials/glide-image-resizing-scaling)

**Comment by hksfho** [comment]
I need to stopAutoCycle(); and removeAllSliders(); before add new image?

**Comment by hksfho** [comment]
The ram will not decrease after listview item released

**Comment by firdausmaulan** [comment]
Try add override on RequestOption
`RequestOptions requestOptions = new RequestOptions();
        requestOptions.override(200,200);`
200 mean in pixel, you can change it as you want.
