### ISSUE TITLE
Custom View

### ISSUE THREAD

**Issue by Errichamonda** [firdausmaulan/GlideSlider#18]
How can I use a custom view for the slider?

I've tried creating a class implementing BaseSliderView but bindEventAndShow is private.

**Comment by JEKos** [comment]
Same, @firdausmaulan can you help here please?

**Comment by firdausmaulan** [comment]
Thank you. I already fix the problem in new release 1.3.0

**Comment by Errichamonda** [comment]
I have another problem, when I try to create the custom view for the Slider it throws an error on a .setBackgroundColor (null pointer exception) line 113 of BaseSliderView. It seems that the color is missing and I can't change it
