### ISSUE TITLE
Avoid AppGlideModule in libraries

### ISSUE THREAD

**Issue by Golgorz** [firdausmaulan/GlideSlider#23]
It is imposible to use this library with our custom AppGlideModule...i think its because of SVG useing its own.
Please remove this form library as suggested in Glide's documentation:
http://bumptech.github.io/glide/doc/configuration.html#avoid-appglidemodule-in-libraries

**Comment by NewITCorp** [comment]
I got this problem too, please manage to fix it

**Comment by firdausmaulan** [comment]
Already removed on new version. Thanks.
