### ISSUE TITLE
cannot add curve the edges of sliderlayout

### ISSUE THREAD

**Issue by personalprojectsus** [firdausmaulan/GlideSlider#26]
I tried adding drawable background in slider layout, it doesn't work. How to achieve it?

**Comment by AnannaRahman** [comment]
facing the same problem

**Comment by firdausmaulan** [comment]
sorry for late reply.
you can try it on new version 1.4.0
change / override it via style.xml

**Comment by nirzonpop192** [comment]
I tried to override the style but fail.. would u show me how to override the style
