### ISSUE TITLE
dependency

### ISSUE THREAD

**Issue by wasimakram007** [firdausmaulan/GlideSlider#29]
implementation 'com.github.firdausmaulan:GlideSlider:1.3.1'
implementation 'com.github.firdausmaulan:GlideSlider:1.3.2'
These are error dependency. these are not getting sync.

**Comment by firdausmaulan** [comment]
Have you add jitpack.io in your repositories?
`repositories {
        google()
        jcenter()
        mavenCentral()
        maven {
            url "https://jitpack.io"
        }
    }`
