### ISSUE TITLE
Support com.bumptech.glide.load.model.GlideUrl

### ISSUE THREAD

**Issue by wilhei** [firdausmaulan/GlideSlider#32]
I can not load images from my REST-Server because I can not authenticate.

Till now i used the GlideUrl for authorization:

`GlideUrl urlWithHeader = new GlideUrl(url, new LazyHeaders.Builder().addHeader("Authorization", Credentials.basic(loggedInUser.getEmail(), loggedInUser.getPassword())).build());`
`return urlWithHeader;`

And then loading the image with the GlideUrl
`Glide.with(context).load(urlWithHeader).into(...);`

How can I authenticate in GlideSlider to be able to load the images?

Tanks and kind regards from Germany,
wilhei

**Comment by jkydevelopment** [comment]
I have exactly the same problem... Did you finally get the solution?

**Comment by firdausmaulan** [comment]
sorry for late reply.
you can try it on new version 1.4.0

**Comment by firdausmaulan** [comment]
```
        ArrayList<GlideUrl> listUrl = new ArrayList<>();

        LazyHeaders headers = new LazyHeaders.Builder()
                .addHeader("Authorization", "Bearer " + token)
                .build();
        GlideUrl glideUrl = new GlideUrl("image_url", headers);
        listUrl.add(glideUrl);
```

**Comment by joaogalli** [comment]
How to use this?

```
val glideUrl = GlideUrl(user?.imagePath, LazyHeaders.Builder()
                            .addHeader("Authorization", "Bearer ${user?.accessToken}").build()
                    )
sliderView.image(glideUrl.toStringUrl())
```

Is this right?
