### ISSUE TITLE
First loading animation remove?

### ISSUE THREAD

**Issue by AlinaPohl** [firdausmaulan/GlideSlider#37]
When I first load images in the view there is an animation I don't want to have, how can I disable it?

Thanks in advance

**Comment by firdausmaulan** [comment]
user / override this on your style.xml and set visibility to gone or invisible
```xml
<style name="GlideSliderLoadingStyle" parent="Base.Widget.AppCompat.ProgressBar">
        <item name="android:layout_height">wrap_content</item>
        <item name="android:layout_width">wrap_content</item>
        <item name="android:layout_centerInParent">true</item>
    </style>
```

**Comment by AlinaPohl** [comment]
I meant the animation from the image/s, when they get into the view

**Comment by firdausmaulan** [comment]
Sorry, I still don't get it.
you meant to change the animation? like this??
mDemoSlider.setPresetTransformer(SliderLayout.Transformer.Default);

**Comment by AlinaPohl** [comment]
Yes, I found 'mDemoSlider.setPresetTransformer(SliderLayout.Transformer.disable);', but that's not available..

**Comment by firdausmaulan** [comment]
O. yes it's not available for now.

**Comment by paixols** [comment]
Hello, will this feature be available soon?

**Comment by firdausmaulan** [comment]
> Hello, will this feature be available soon?

Hmm.. I guest not for now..
Actually you can customize this library and add it on your project.
http://www.vogella.com/tutorials/AndroidLibraryProjects/article.html
