### ISSUE TITLE
Disable AutoPause in MotionEvent

### ISSUE THREAD

**Issue by Brumanuel** [firdausmaulan/GlideSlider#40]
The slider stops when you move your finger on it (no necessary changing the slide), can i disable this autoPause? 

 ```
 @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        int action = ev.getAction();
        switch (action) {
            case MotionEvent.ACTION_DOWN:
                pauseAutoCycle();
                break;
        }
        return false;
    }
```

**Comment by firdausmaulan** [comment]
Actually you can customize this library and add it on your project.
http://www.vogella.com/tutorials/AndroidLibraryProjects/article.html

**Comment by firdausmaulan** [comment]
I already add new method for it
stopCyclingWhenTouch(boolean)
