### ISSUE TITLE
How to configure cache ?

### ISSUE THREAD

**Issue by Sulistyarif** [firdausmaulan/GlideSlider#41]
I want to have a cache system,
- when internet connected, always download from URL
- when internet disconnected, always load from cache 
how to make it ?
i was try using RequestOptions and its not work, or is it my configuration false ?

my code :
 
RequestOptions requestOptions = new RequestOptions();
requestOptions.centerCrop();

if (isNetworkConnected()){

            requestOptions.signature(new ObjectKey(Long.toString(System.currentTimeMillis())));
            requestOptions.diskCacheStrategy(DiskCacheStrategy.RESOURCE);
            requestOptions.skipMemoryCache(false);

}

**Comment by firdausmaulan** [comment]
I think glide has auto cache as a default. so, you not need to configure any caching strategy.
