### ISSUE TITLE
BaseSliderView.image(Glide glideUrl) should be image(GlideUrl glideUrl)

### ISSUE THREAD

**Issue by joaogalli** [firdausmaulan/GlideSlider#45]
The class BaseSliderView should accept a GlideUrl in the method image().

or is there a way to pass a Glide object to it?

**Comment by firdausmaulan** [comment]
Yes it should be GlideUrl
already fix on new version 1.4.1

**Comment by joaogalli** [comment]
Nice, it works great. Thanks.
