### ISSUE TITLE
No field glide_slider_viewpager

### ISSUE THREAD

**Issue by samuelhalim1** [firdausmaulan/GlideSlider#46]
Why i always get this error?
No field glide_slider_viewpager of type I in class Lcom/glide/slider/library/R$id; or its superclasses (declaration of 'com.glide.slider.library.R$id' appears in /data/app/testing/split_lib_slice_2_apk.apk)

**Comment by firdausmaulan** [comment]
Maybe it can help
[https://developer.android.com/studio/build/multidex](https://developer.android.com/studio/build/multidex)
