### ISSUE TITLE
How to round corners in GlideSlider?

### ISSUE THREAD

**Issue by vahab-asefi** [firdausmaulan/GlideSlider#49]
Hello and thank you for all your efforts in android development.

I have one issue with this your library:

How can I create a slider layout with rounded corners as you create in the image below?

https://camo.githubusercontent.com/90c532d9dff59932ce8cbda40751e349b27fc146/68747470733a2f2f73322e67696679752e636f6d2f696d616765732f676c6964655f736c696465722e676966

**Comment by firdausmaulan** [comment]
add this to your style.xml

```xml
<style name="GlideSliderCardStyle" parent="Base.CardView">
        <item name="android:layout_height">match_parent</item>
        <item name="android:layout_width">match_parent</item>
        <item name="cardCornerRadius">8dp</item>
</style>
```

**Comment by vahab-asefi** [comment]
Thank you very much but it does not work for me. Should I add this style in runtime? 

might it be a special issue with CardView in my project?

**Comment by firdausmaulan** [comment]
make sure the directory is correct
res/values/styles.xml

**Comment by vahab-asefi** [comment]
I've just check it. it is correct. this my layout:

`<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:layout_behavior="@string/appbar_scrolling_view_behavior"
    tools:context="com.separak.telemarket.MainActivity"
    tools:showIn="@layout/app_bar_main2">

    <android.support.constraint.ConstraintLayout
        android:id="@+id/cl_search"
        android:layout_width="match_parent"
        android:layout_height="?android:attr/actionBarSize"
        android:background="@color/colorPrimary"
        android:elevation="@dimen/margin_small"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent">

        <android.support.constraint.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginStart="@dimen/margin_large"
            android:layout_marginTop="@dimen/margin_small"
            android:layout_marginEnd="@dimen/margin_large"
            android:layout_marginBottom="@dimen/margin_large"
            android:background="@drawable/bac_search">

            <ImageView
                android:id="@+id/imageViewSearch"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginRight="@dimen/margin_medium"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintRight_toRightOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                app:srcCompat="@drawable/magnify" />

            <android.support.v7.widget.AppCompatTextView
                android:id="@+id/tvS_sarch"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginStart="@dimen/margin_ten"
                android:layout_marginEnd="@dimen/margin_ten"
                android:hint="@string/search_hint"
                android:maxLines="1"
                android:textSize="12sp"
                app:fontFamily="@font/irsans"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintLeft_toLeftOf="parent"
                app:layout_constraintRight_toLeftOf="@+id/imageViewSearch"
                app:layout_constraintTop_toTopOf="parent" />


        </android.support.constraint.ConstraintLayout>

    </android.support.constraint.ConstraintLayout>

    <android.support.v4.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/cl_search">

        <android.support.constraint.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <FrameLayout
                android:id="@+id/frm_main"
                android:layout_width="match_parent"
                android:layout_height="160dp"
                android:layout_margin="@dimen/margin_large"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent">

                <com.glide.slider.library.SliderLayout
                    android:id="@+id/main_slider"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent" />

            </FrameLayout>

            <android.support.v7.widget.RecyclerView
                android:id="@+id/rv_nan"
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:padding="@dimen/margin_medium"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/frm_main" />

        </android.support.constraint.ConstraintLayout>

    </android.support.v4.widget.NestedScrollView>


</android.support.constraint.ConstraintLayout>
`

**Comment by vahab-asefi** [comment]
thank you anyway

**Comment by firdausmaulan** [comment]
try to add style="@style/GlideSliderCardStyle" to your layout
```xml
<com.glide.slider.library.SliderLayout
                android:id="@+id/main_slider"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                style="@style/GlideSliderCardStyle" />
```

**Comment by vahab-asefi** [comment]
I've done it, but it still does not work properly.

**Comment by vahab-asefi** [comment]
The problem has been solved using the code below for RequestOptions defenition:

`RequestOptions requestOptions = new RequestOptions();

        requestOptions = requestOptions.transform(new CenterCrop(), new RoundedCorners(32)); //added
        
         requestOptions
                //.centerCrop()  //commented
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .placeholder(R.drawable.logo_512)
                .error(R.drawable.alert_circle);`

And by adding two style tags as below:

`<style name="GlideSliderBackgroundStyle">
        <item name="android:layout_height">match_parent</item>
        <item name="android:layout_width">match_parent</item>
        <item name="android:background">@color/transparent</item>
    </style>

    <style name="GlideSliderImageStyle">
        <item name="android:layout_height">match_parent</item>
        <item name="android:layout_width">match_parent</item>
        <item name="android:background">@color/transparent</item>
    </style>`

**Comment by SheharyarEjaz** [comment]
not working for me!

**Comment by SheharyarEjaz** [comment]
Can u elaborate it !
