### ISSUE TITLE
Rounded Image Slider like in sample project ?

### ISSUE THREAD

**Issue by SheharyarEjaz** [firdausmaulan/GlideSlider#54]
How can we achieve the Image Slider like you show here

https://camo.githubusercontent.com/90c532d9dff59932ce8cbda40751e349b27fc146/68747470733a2f2f73322e67696679752e636f6d2f696d616765732f676c6964655f736c696465722e676966

**Comment by firdausmaulan** [comment]
add this to your style.xml
```
<style name="GlideSliderCardStyle" parent="Base.CardView">
        <item name="android:layout_height">match_parent</item>
        <item name="android:layout_width">match_parent</item>
        <item name="cardCornerRadius">XXdp</item>
</style>
```
