### ISSUE TITLE
transparent background

### ISSUE THREAD

**Issue by m-grzegorczyk** [firdausmaulan/GlideSlider#55]
Hi,

how can I get transparent background?
If I f.e. set solid color in:
`<color name="glide_slider_background_color">#00FF00</color>`
or via
`slider.setBackgroundColor(Color.RED);`

it works fine, but when I set color to transparent, like:
`<color name="glide_slider_background_color">#0000FF00</color>`
or via
`slider.setBackgroundColor(Color.TRANSPARENT);`

background is white, not transparent...

**Comment by firdausmaulan** [comment]
you have to add this on your style.xml

`
<style name="GlideSliderCardStyle" parent="Base.CardView">
        <item name="android:layout_height">match_parent</item>
        <item name="android:layout_width">match_parent</item>
        <item name="cardBackgroundColor">@android:color/transparent</item>
</style>
`
