### ISSUE TITLE
How can remove indicator and fit image to slide

### ISSUE THREAD

**Issue by junoprima** [firdausmaulan/GlideSlider#8]
How can remove indicator and fit image to slide it size i get over slide screen how can fit it

**Comment by firdausmaulan** [comment]
If you watn to hide indicator, you can use DefaultSliderView instead of TextSliderView.
And you want to fit image, you can use .setBitmapTransformation method follow this [example](https://github.com/firdausmaulan/GlideSlider-Example/blob/feature/1.0.2/app/src/main/java/com/glide/slider/example/MainActivity.java) for more detail.

**Comment by junoprima** [comment]
DefaultSliderView how can but on the code this below

`String img_name = mainboard.getMb_pic();

                img_name.split(",");

                ArrayList<String> listUrl = new ArrayList<String>();
                listUrl.add(path_image + img_name + "?alt=media");

                for (int i = 0 ; i< listUrl.size(); i++){
                    TextSliderView textSliderView = new TextSliderView(getApplicationContext());

                    textSliderView
                            .image(listUrl.get(i))
                            .setBitmapTransformation(new CenterCrop());
                    mSlide.addSlider(textSliderView);
                }`

and i set bitmap same problem i get oversize of slide

**Comment by firdausmaulan** [comment]
`DefaultSliderView sliderView = new DefaultSliderView(getApplicationContext());

    sliderView
		.image(listUrl.get(i))
		.setBitmapTransformation(new CenterCrop());
    mSlide.addSlider(sliderView);`

May I know your image size in pixel? maybe it's smaller than slider view size.
