### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by prokash-sarkar** [firdausmaulan/GlideSlider#9]
Can't use the newest version of Glide along with the default one given with library. I'm using the following Glide dependencies explicitly:

```
annotationProcessor 'com.github.bumptech.glide:compiler:4.4.0'
implementation 'com.github.firdausmaulan:GlideSlider:1.0.2'
```

This throws a **java.lang.NoSuchMethodError** :

 ```
 java.lang.NoSuchMethodError: No virtual method into(Landroid/widget/ImageView;)Lcom/bumptech/glide/request/target/Target; in class Lcom/bumptech/glide/RequestBuilder; or its super classes (declaration of 'com.bumptech.glide.RequestBuilder' appears in /data/app/com.sslwireless.starcineplex-1/split_lib_dependencies_apk.apk)

at com.glide.slider.library.SliderTypes.BaseSliderView.bindEventAndShow(BaseSliderView.java:268)
at com.glide.slider.library.SliderTypes.TextSliderView.getView(TextSliderView.java:25)
at com.glide.slider.library.SliderAdapter.instantiateItem(SliderAdapter.java:81)
at com.glide.slider.library.Tricks.InfinitePagerAdapter.instantiateItem(InfinitePagerAdapter.java:54)
at com.glide.slider.library.Tricks.ViewPagerEx.addNewItem(ViewPagerEx.java:848)
at com.glide.slider.library.Tricks.ViewPagerEx.populate(ViewPagerEx.java:998)
at com.glide.slider.library.Tricks.ViewPagerEx.populate(ViewPagerEx.java:930)
at com.glide.slider.library.Tricks.ViewPagerEx.onMeasure(ViewPagerEx.java:1453)
```

**Comment by firdausmaulan** [comment]
Thanks for the feedback.
Ok I'll update to the latest glide library, or maybe you can make a pull request to support latest glide library.

**Comment by Hitexroid** [comment]
I have this problem too.

**Comment by firdausmaulan** [comment]
Ok wait, I have a problem to release new version using Gradle 4.1
[https://jitpack.io/docs/ANDROID/](https://jitpack.io/docs/ANDROID/)

**Comment by poplevente** [comment]
Hey, did you manage to fix the issue? i'm also getting this error

**Comment by firdausmaulan** [comment]
I still have a problem to release new version using Gradle 4.1

https://jitpack.io/com/github/firdausmaulan/GlideSlider/1.0.3/build.log

**Comment by firdausmaulan** [comment]
I already make new release.
So, you can use the latest version of this library
implementation 'com.github.firdausmaulan:GlideSlider:1.1.0'

Thanks to [@ar-android](https://github.com/ar-android/), for helping make new release.

**Comment by Hitexroid** [comment]
@poplevente Unfortunately i'm using old version of glide

**Comment by Hitexroid** [comment]
@firdausmaulan Thank you buddy .
i'll test it now .

**Comment by Hitexroid** [comment]
![screenshot 168](https://user-images.githubusercontent.com/19854097/34600825-b40ba6aa-f20e-11e7-8ba9-7e97424b2371.png)

Why is it so long ?

**Comment by firdausmaulan** [comment]
May I know your gradle version?
Please use version 3.0.1 or 3.0.0
classpath 'com.android.tools.build:gradle:3.0.1'

If you use old version of Glide, you can use GlideSlider version 1.0.1 / 1.0.2.

**Comment by Hitexroid** [comment]
My gradle version is `classpath 'com.android.tools.build:gradle:3.0.1'`

**Comment by paveltech** [comment]
I also facing this issue but i solved this using latest version of glide

 implementation 'com.github.bumptech.glide:glide:4.9.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'
